import Header from "@/src/components/layouts/Header"
import Footer from "@/src/components/layouts/Footer"
import "./globals.css"
import type { Metadata } from "next"
import { Poppins } from "next/font/google"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Joseph Web's",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`min-h-screen ${poppins.className}`}>
        <Header />
        {children}
        <Footer />
        {modal}
      </body>
    </html>
  )
}
